# Generated by Django 5.1.6 on 2026-09-03 05:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('total_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('remaining_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('utilization_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_summaries', to='departments.department')),
            ],
            options={
                'ordering': ['-year', '-month', 'department__name'],
                'indexes': [models.Index(fields=['department', 'year', 'month'], name='reports_bud_departm_47f7e9_idx')],
                'constraints': [models.UniqueConstraint(fields=('department', 'month', 'year'), name='uq_budget_summary_department_month_year')],
            },
        ),
    ]
