# Generated by Django 5.1.6 on 2026-09-03 05:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^INC-\\d{6}$', 'Use the format INC-000001.')])),
                ('source', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('income_date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_records', to='categories.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_records', to='departments.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-income_date', '-created_at'],
                'indexes': [models.Index(fields=['department', 'income_date'], name='income_inco_departm_ef2ed3_idx'), models.Index(fields=['category', 'income_date'], name='income_inco_categor_fa8ea0_idx'), models.Index(fields=['status', 'income_date'], name='income_inco_status_31ebc3_idx')],
            },
        ),
    ]
